###########
# site.title

title:    'mingh2/SurvivalOfTheFittest'^M
subtitle: 'CS 175: Project in AI (in Minecraft)'^M

name:         'Survival of The Fittest'^M
description:  'Minecraft Malmo Project for CS 175 at UC Irvine'^M

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
