###########
# site.title

title:    'mingh2/SurvivalOfTheFittest'
subtitle: 'CS 175: Project in AI (in Minecraft)'

name:         'Survival of The Fittest'
description:  'Minecraft Malmo Project for CS 175 at UC Irvine'

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
