###########
# site.title

title:    'Survival of The Fittest'
subtitle: 'CS 175: Project in AI (in Minecraft)'

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
